spring.application.name=auth-service
server.port=8081

spring.datasource.url=jdbc:postgresql://${AUTH_DB_HOST:localhost}:${AUTH_DB_PORT:5432}/auth_db
spring.datasource.username=${AUTH_DB_USERNAME:auth_service}
spring.datasource.password=${AUTH_DB_PASSWORD:2210Ngahoang.@}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.default_schema=auth
spring.jpa.open-in-view=false
