spring.application.name=auth-service
spring.config.import=optional:classpath:mailtemplate.properties
server.port=8081

spring.datasource.url=jdbc:postgresql://${AUTH_DB_HOST:localhost}:${AUTH_DB_PORT:5432}/auth_db
spring.datasource.username=${AUTH_DB_USERNAME:auth_service}
spring.datasource.password=${AUTH_DB_PASSWORD:2210Ngahoang.@}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.default_schema=auth
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.schemas=auth
spring.flyway.default-schema=auth

# Swagger OpenAPI config
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.display-request-duration=true

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=hungmemory01@gmail.com
spring.mail.password=gudwybpgjnqvujet
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# JWT Configuration
jwt.secretKey=${JWT_SECRET:357638792F423F4428472B4B6250655368566D597133743677397A2443264629}
jwt.expiration=900000
jwt.refresh-expiration=604800000
jwt.type=Bearer

MAX.OTP.FAILED.ATTEMPTS=5
app.otp.change-password-expiration-minutes=5
app.otp.forgot-password-expiration-minutes=10

# Pagination Configuration
route.pageSize=10
company.pageSize=10

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB
spring.thymeleaf.check-template-location=false

cloudinary.cloudName=dixe4ybxu
cloudinary.apiKey=899278923884326
cloudinary.apiSecret=O8HZWpijOWUicZjv8zX2KDbPrqo
cloudinary.secure=true

# Upload constraints
app.avatar.max-size-bytes=2097152

# Default avatar and role
app.avatar.default-url=https://www.facebook.com/groups/androidvatvostudio/posts/1045229810299978/
app.default-role=USER
app.admin-role=ADMIN

# I18n message configuration
spring.messages.basename=messages
spring.messages.fallback-to-system-locale=false
spring.messages.use-code-as-default-message=true


