spring.application.name=payment-service
server.port=8084

spring.datasource.url=jdbc:postgresql://${PAYMENT_DB_HOST:localhost}:${PAYMENT_DB_PORT:5432}/payment_db
spring.datasource.username=${PAYMENT_DB_USERNAME:payment_service}
spring.datasource.password=${PAYMENT_DB_PASSWORD:REDACTED_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.default_schema=payment
spring.jpa.open-in-view=false
