spring.application.name=order-service
server.port=8082

spring.datasource.url=jdbc:postgresql://${ORDER_DB_HOST:localhost}:${ORDER_DB_PORT:5432}/order_db
spring.datasource.username=${ORDER_DB_USERNAME:order_service}
spring.datasource.password=${ORDER_DB_PASSWORD:REDACTED_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.default_schema=orders
spring.jpa.open-in-view=false
