spring.application.name=order-service
server.port=8082

spring.datasource.url=jdbc:postgresql://${ORDER_DB_HOST:localhost}:${ORDER_DB_PORT:5432}/order_db
spring.datasource.username=${ORDER_DB_USERNAME:order_service}
spring.datasource.password=${ORDER_DB_PASSWORD:REDACTED_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.default_schema=orders
spring.jpa.open-in-view=false

# Swagger OpenAPI config
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.display-request-duration=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.schemas=orders
spring.flyway.default-schema=orders

app.order.code-prefix=ORD
app.order.default-currency=VND

# JWT configuration for resource server
jwt.secretKey=${JWT_SECRET:REDACTED_JWT_SECRET}
