spring.application.name=notification-service
server.port=8085

spring.datasource.url=jdbc:postgresql://${NOTIFICATION_DB_HOST:localhost}:${NOTIFICATION_DB_PORT:5432}/notification_db
spring.datasource.username=${NOTIFICATION_DB_USERNAME:notification_service}
spring.datasource.password=${NOTIFICATION_DB_PASSWORD:2210Ngahoang.@}
